version: '2'

services:
  server:
    build: ./server
    volumes_from:
      - volumes_data
    ports:
      - "8080:80"
  volumes_data:
    image: tianon/true
    volumes:
      - ./www:/var/www/html
