version: '2'

services:
  server:
    build: ./server
    volumes_from:
      - volumes_data
    ports:
      - "80:80"
  volumes_data:
    image: tianon/true
    volumes:
      - ../image-server:/var/www/html
